platform :ios, '8.0'

target 'WMall' do

pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'FMDB'
pod 'SDWebImage'
pod 'TZImagePickerController'
pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'CDDPagerController'
pod 'ZYCornerRadius'
pod 'ZXingObjC'

end

